# https://github.com/leonardcser/cursortab.nvim - autocompletion with AI
return {}
-- return {
--   {
--     "leonardcser/cursortab.nvim",
--     build = "cd server && go build -o cursortab .",
--     event = "InsertEnter", -- TODO: This is not working
--     config = function()
--     require("cursortab").setup({
--       -- CUSTOMIZATION
--       deletion_color = "#Df9f9f",
--       addition_color = "#87d37c",
--       modification_color = "#FFFF99",
--       completion_color = "#80899c",
--       jump_bg_color = "#373b45",
--       jump_fg_color = "#bac1d1",
-- --      deletion_color = "#4f2f2f",
-- --      addition_color = "#394f2f",
-- --      modification_color = "#282e38",
-- --      completion_color = "#80899c",
-- --      jump_bg_color = "#373b45",
-- --      jump_fg_color = "#bac1d1",
--       jump_symbol = "",
--       jump_text = " TAB ",
--       jump_show_distance = true,
-- 
--       -- OPTIONS
--       enabled = true,
--       provider = "autocomplete",
--       idle_completion_delay = 50,
--       text_changed_debounce = 50,
-- 
--       -- CONTEXT OPTIONS
--       max_context_tokens = 1024,
-- 
--       -- PROVIDER OPTIONS
--       provider_url = "http://localhost:11434",
--       provider_model = "hf.co/sweepai/sweep-next-edit-1.5B:latest",
--       provider_temperature = 0.0,
--       provider_max_tokens = 50,
--       provider_top_k = 50,
--     })
--     end
--   },
-- }
-- 
